<%@ Page Title="" Language="C#" MasterPageFile="~/MainMaster.Master" AutoEventWireup="true" CodeBehind="CartDetail.aspx.cs" Inherits="FD_1.PlaceOrder" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <%--for fetching data for card we use store procedures viewUserCart--%>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:FD_1ConnectionString %>" SelectCommand="viewUserCart" SelectCommandType="StoredProcedure">
        <SelectParameters>
            <asp:SessionParameter Name="email" SessionField="CustomerIn" Type="String" />
        </SelectParameters>
    </asp:SqlDataSource>

    <div class="container-fluid">
        <div class="row flex-column-reverse flex-lg-row p-3">
            <div class="col-lg-8 col-md-12">
                <h1 class="text-center mb-3">Your Card
                </h1>
                <%--<asp:GridView ID="GridView1" runat="server" DataSourceID="SqlDataSource1" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
                            
                        </asp:GridView>--%>

                <div class="container-fluid ml-lg-5">
                    <div class="row">
                        <div class="col-lg-12 col-sm-12">

                            <asp:DataList ID="DataList1" CssClass="row" runat="server" DataSourceID="SqlDataSource1" AutoGenerateColumns="False" RepeatDirection="Horizontal" RepeatLayout="Flow" OnItemCommand="DataList1_ItemCommand">
                                <EditItemTemplate>
                                    <div class="card mb-3">
                                        <div class="row no-gutters">
                                            <div class="col-md-4">
                                                <asp:Image ID="Image1" CssClass="mt-5" runat="server" ImageUrl='<%# Bind("pimg") %>' Width="100%" />
                                            </div>
                                            <div class="col-md-8">
                                                <div class="card-body" style="width: 300px;">
                                                    <h5 class="card-title">Cart id:<asp:Label ID="cartid1" runat="server" Text='<%# Bind("cartid") %>'></asp:Label>
                                                        Product id:<asp:Label ID="pid1" runat="server" Text='<%# Bind("pid") %>'></asp:Label>
                                                        <br />
                                                        <asp:Label ID="pname1" runat="server" Text='<%# Bind("pname") %>'></asp:Label>
                                                    </h5>
                                                    <p class="card-text">
                                                        <small class="text-muted">Categories: 
                                                        <asp:Label ID="pcategories1" runat="server" Text='<%# Bind("pcategories") %>'></asp:Label>
                                                            Description:
                                                        <asp:Label ID="pdescription1" runat="server" Text='<%# Bind("pdescription") %>'></asp:Label>
                                                            Shop id:
                                                        <asp:Label ID="pshopid1" runat="server" Text='<%# Bind("pshopid") %>'></asp:Label>
                                                        </small>
                                                    </p>
                                                    <p class="card-text mt-3">
                                                        Rs 
                                                      <asp:Label ID="pprice1" runat="server" Text='<%# Bind("pprice","{0} Rs") %>'></asp:Label>
                                                    </p>
                                                    <p class="card-text mt-3">
                                                        Added At:
                                                    <asp:Label ID="cdate1" runat="server" Text='<%# Bind("cdate") %>'></asp:Label>
                                                    </p>
                                                    <p class="card-text mt-3">
                                                        Quantity
                                                        <%--this below text box give error if remove so we do visible="false"--%>
                                                        <asp:TextBox ID="newQuantity" runat="server" TextMode="Number" Text='<%# Bind("quantity") %>' Visible="False"></asp:TextBox>
                                                        <asp:DropDownList ID="DropDownListQuantity" runat="server" Width="80">
                                                            <asp:ListItem>1</asp:ListItem>
                                                            <asp:ListItem>2</asp:ListItem>
                                                            <asp:ListItem>3</asp:ListItem>
                                                            <asp:ListItem>4</asp:ListItem>
                                                            <asp:ListItem>5</asp:ListItem>
                                                        </asp:DropDownList>
                                                        <asp:Label ID="quantity1" runat="server" Text='<%# Bind("quantity") %>'></asp:Label>
                                                        <asp:LinkButton ID="changequantity1" runat="server" CssClass="btn btn-secondary btn-sm btn-sm" CommandName="updateQuantity">
                                                        <i class="fa fa-check" aria-hidden="true"></i>Done
                                                        </asp:LinkButton>
                                                    </p>
                                                    <p class="card-text mt-3">
                                                        Total Price:
                                                    <asp:Label ID="itemTotalPrice1" runat="server" Text='<%# Bind("ItemTotalPrice") %>'></asp:Label>
                                                    </p>
                                                    <%--<div class="col-lg-12 col-sm-12">
                                                        <asp:LinkButton ID="btnRemoveCart1" runat="server" CssClass="btn btn-danger btn align-content-lg-around btn-block" CommandName="removeFromCart">
                                                        <i class="fa fa-times" aria-hidden="true"></i>Remove From Cart
                                                        </asp:LinkButton>
                                                    </div>--%>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </EditItemTemplate>

                                <ItemTemplate>
                                    <div class="card mb-3">
                                        <div class="row no-gutters">
                                            <div class="col-md-4">
                                                <asp:Image ID="Image2" CssClass="mt-5" runat="server" ImageUrl='<%# Bind("pimg") %>' Width="100%" />
                                            </div>
                                            <div class="col-md-8">
                                                <div class="card-body" style="width: 300px;">
                                                    <h5 class="card-title">Cart id:<asp:Label ID="cartid" runat="server" Text='<%# Bind("cartid") %>'></asp:Label>
                                                        Product id:<asp:Label ID="pid" runat="server" Text='<%# Bind("pid") %>'></asp:Label>
                                                        <br />
                                                        <asp:Label ID="pname" runat="server" Text='<%# Bind("pname") %>'></asp:Label>
                                                    </h5>
                                                    <p class="card-text">
                                                        <small class="text-muted">Categories: 
                                                        <asp:Label ID="pcategories" runat="server" Text='<%# Bind("pcategories") %>'></asp:Label>
                                                            Description:
                                                        <asp:Label ID="pdescription" runat="server" Text='<%# Bind("pdescription") %>'></asp:Label>
                                                            Shop id:
                                                        <asp:Label ID="pshopid" runat="server" Text='<%# Bind("pshopid") %>'></asp:Label>
                                                        </small>
                                                    </p>
                                                    <p class="card-text mt-3">
                                                        Rs 
                                                      <asp:Label ID="pprice" runat="server" Text='<%# Bind("pprice","{0} Rs") %>'></asp:Label>
                                                    </p>
                                                    <p class="card-text mt-3">
                                                        Added At:
                                                    <asp:Label ID="cdate" runat="server" Text='<%# Bind("cdate") %>'></asp:Label>
                                                    </p>
                                                    <p class="card-text mt-3">
                                                        Quantity:
                                                    <%--<EditItemTemplate>
                                                        <asp:TextBox ID="newQuantity" runat="server" TextMode="Number" Text='<%# Bind("quantity") %>'></asp:TextBox>
                                                    </EditItemTemplate>--%>
                                                        <asp:Label ID="quantity" runat="server" Text='<%# Bind("quantity") %>'></asp:Label>
                                                        <asp:LinkButton ID="changequantity" runat="server" CssClass="btn btn-secondary btn-sm btn-sm" CommandName="addQuantity">
                                                        <i class="fa fa-plus" aria-hidden="true"></i>Add
                                                        </asp:LinkButton>
                                                    </p>
                                                    <p class="card-text mt-3">
                                                        Total Price:
                                                    <asp:Label ID="ItemTotalPrice" runat="server" Text='<%# Bind("ItemTotalPrice","{0} Rs") %>'></asp:Label>
                                                    </p>
                                                    <div class="col-lg-12 col-sm-12">
                                                        <asp:LinkButton ID="btnRemoveCart" runat="server" CssClass="btn btn-danger btn-lg btn-block" CommandName="removeFromCart">
                                                        <i class="fa fa-times" aria-hidden="true"></i>Remove From Cart
                                                        </asp:LinkButton>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </ItemTemplate>
                            </asp:DataList>

                        </div>

                        <%--<Columns>
                                <asp:BoundField DataField="cartid" HeaderText="cartid" InsertVisible="False" ReadOnly="True" SortExpression="cartid" />
                                <asp:TemplateField HeaderText="pid" SortExpression="pid">
                                    <ItemTemplate>
                                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("pid") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="cdate" SortExpression="cdate">
                                    <ItemTemplate>
                                        <asp:Label ID="Label9" runat="server" Text='<%# Bind("cdate") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="quantity" SortExpression="quantity">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("quantity") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("quantity") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="pname" SortExpression="pname">
                                    <ItemTemplate>
                                        <asp:Label ID="Label3" runat="server" Text='<%# Bind("pname") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="pdescription" SortExpression="pdescription">
                                    <ItemTemplate>
                                        <asp:Label ID="Label4" runat="server" Text='<%# Bind("pdescription") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="pprice" SortExpression="pprice">
                                    <ItemTemplate>
                                        <asp:Label ID="Label5" runat="server" Text='<%# Bind("pprice") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="pcategories" SortExpression="pcategories">
                                    <ItemTemplate>
                                        <asp:Label ID="Label6" runat="server" Text='<%# Bind("pcategories") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="pimg" SortExpression="pimg">
                                    <ItemTemplate>
                                        <asp:Image ID="Image1" runat="server" ImageUrl='<%# Bind("pimg") %>' Width="50%"/>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="pshopid" SortExpression="pshopid">
                                    <ItemTemplate>
                                        <asp:Label ID="Label8" runat="server" Text='<%# Bind("pshopid") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                            </Columns>--%>

                        <%--<div class="col-lg-6 col-sm-6">
                        <div class="card mb-3">
                            <div class="row no-gutters">
                                <div class="col-md-4">
                                    <img src="\img/product/b1.jpg" style="width:100%;">
                                </div>
                                <div class="col-md-8">
                                    <div class="card-body">
                                        <h5 class="card-title">Good Day</h5
                                        <p class="card-text"><small class="text-muted">biscute with tea and coffe</small></p>
                                            <select class="custom-select">
                                              <option value="1" selected>1</option>
                                              <option value="2">2</option>
                                              <option value="3">3</option>
                                              <option value="4">4</option>
                                            </select>
                                        <p class="card-text mt-3">Rs 60</p>
                                        <button type="button" class="btn btn-danger">Remove</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-sm-6">
                        <div class="card mb-3">
                            <div class="row no-gutters">
                                <div class="col-md-4">
                                    <img src="\img/product/b1.jpg" style="width:100%;">
                                </div>
                                <div class="col-md-8">
                                    <div class="card-body">
                                        <h5 class="card-title">Good Day</h5
                                        <p class="card-text"><small class="text-muted">biscute with tea and coffe</small></p>
                                            <select class="custom-select">
                                              <option value="1" selected>1</option>
                                              <option value="2">2</option>
                                              <option value="3">3</option>
                                              <option value="4">4</option>
                                            </select>
                                        <p class="card-text mt-3">Rs 60</p>
                                        <button type="button" class="btn btn-danger">Remove</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>--%>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-12">
                <%--this sqldatasource contain storeProcedure-totalPiceCart for the getting the total price and count of product of cart--%>
                <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:FD_1ConnectionString %>" SelectCommand="totalPriceCart" SelectCommandType="StoredProcedure">
                    <SelectParameters>
                        <asp:SessionParameter Name="email" SessionField="CustomerIn" Type="String" />
                    </SelectParameters>
                </asp:SqlDataSource>

                <div class="row">
                    <h1 class="text-center mb-3">Price</h1>
                    <div class="col-lg-12 col-md-12">

                        <asp:DataList ID="DataList2" runat="server" DataSourceID="SqlDataSource2"  AutoGenerateColumns="False" RepeatDirection="Horizontal" RepeatLayout="Flow">
                            <ItemTemplate>
                                <div class="card p-3">
                                    <div class="row no-gutters">
                                        <div class="col-lg-6 mt-2">
                                            <p class="card-text">Number Product</p>
                                        </div>
                                        <div class="col-lg-6 mt-2">
                                            <p class="card-text float-right">
                                               <asp:Label ID="Label2" runat="server" Text='<%# Eval("ProductCount") %>'></asp:Label>
                                            </p>
                                        </div>
                                    </div>
                                    <hr />
                                    <div class="row no-gutters">
                                        <div class="col-lg-6 mt-2">
                                            <p class="card-text">Total Charge</p>
                                        </div>
                                        <div class="col-lg-6 mt-2">
                                            <p class="card-text float-right">
                                                <asp:Label ID="totalPrice" runat="server" Text='<%# Eval("totalPrice") %>'></asp:Label>
                                            </p>
                                        </div>
                                    </div>
                                    <div class="row no-gutters">
                                        <div class="col-lg-12 mt-4">
                                            <asp:Button ID="btnCheckOut" runat="server" class="btn btn-success btn-lg btn-block mb-2" Text="Check Out" OnClick="btnCheckOut_Click1"/>
                                        </div>
                                    </div>
                                </div>
                            </ItemTemplate>
                        </asp:DataList>
                    </div>
                    <!--<div class="card p-3">
                                    <div class="row no-gutters">
                                        <div class="col-lg-6 mt-2">
                                            <p class="card-text">Number Product</p>
                                        </div>
                                        <div class="col-lg-6 mt-2">
                                            <p class="card-text float-right">
                                               <asp:Label ID="Label2" runat="server" Text='<%# Eval("ProductCount") %>'></asp:Label>
                                            </p>
                                        </div>
                                    </div>
                                    <hr />
                                    <div class="row no-gutters">
                                        <div class="col-lg-6 mt-2">
                                            <p class="card-text">Total Charge</p>
                                        </div>
                                        <div class="col-lg-6 mt-2">
                                            <p class="card-text float-right">
                                                <asp:Label ID="totalPrice" runat="server" Text='<%# Eval("totalPrice") %>'></asp:Label>
                                            </p>
                                        </div>
                                    </div>
                                    <div class="row no-gutters">
                                        <div class="col-lg-12 mt-4">
                                            <asp:Button ID="btnCheckOut" runat="server" class="btn btn-success btn-lg btn-block mb-2" Text="Check Out" OnClick="btnCheckOut_Click1"/>
                                        </div>
                                    </div>
                                </div>-->
                    <%--<Columns>
                                <asp:BoundField DataField="totalPrice" HeaderText="totalPrice" ReadOnly="True" SortExpression="totalPrice" />
                                <asp:BoundField DataField="ProductCount" HeaderText="ProductCount" ReadOnly="True" SortExpression="ProductCount" />
                            </Columns>--%>
                    <%--<div class="col-lg-12 col-sm-12">
                                <div class="card p-3">
                                    <div class="row no-gutters">
                                        <div class="col-md-6 mt-2">
                                            <p class="card-text">Number Product</p>
                                        </div>
                                        <div class="col-md-6 mt-2">
                                            <p class="card-text float-right">40</p>
                                        </div>
                                    </div>
                                    <hr />
                                    <div class="row no-gutters">
                                        <div class="col-md-6 mt-2">
                                            <p class="card-text">Total Charge</p>
                                        </div>
                                        <div class="col-md-6 mt-2">
                                            <p class="card-text float-right">80</p>
                                        </div>
                                    </div>
                                    <div class="row no-gutters">
                                        <div class="col-md-12 mt-4">
                                            <button type="button" class="btn btn-success btn-lg btn-block">Place Order</button>
                                        </div>
                                    </div>
                                </div>
                    </div>--%>
                </div>
            </div>

        </div>
    </div>


</asp:Content>
